#!/bin/bash

nofile()
{
    echo "Insert file to modulize"
    exit 1
}

invalid()
{
    if [[ "$1" != *.c ]]; then
        echo "Invalid file"
        exit 1
    fi
}

FILE=$1 || nofile
invalid $FILE
OBJECT=$(echo $FILE | sed 's/\.c$/.o/')
MODULE=$(echo $FILE | sed 's/\.c$/.so/')

gcc -I/usr/include -I/usr/include/libxml2 -c -o $OBJECT $FILE
gcc -shared -Wl,-soname,$MODULE -o $MODULE $OBJECT
rm $OBJECT
